version: "2"

services:
  hlds:
    image: jearde/hlds:latest
    environment:
      GAME:        "cstrike"
      MAXPLAYERS:  "32"
      START_MAP:   "de_dust2"
      SERVER_NAME: "AI Gaming: CStrike v0.2"
      START_MONEY: "800"
      BUY_TIME:    "1.25"
      FRIENDLY_FIRE:   "1"
      RESTART_ON_FAIL: "1"
      # SERVER_PASSWORD: "secret"
      RCON_PASSWORD:   "supersecret"
    ports:
      - 26900:26900/udp
      - 27020:27020/udp
      - 27015:27015/udp
      - 27015:27015/tcp
      - 80:80/tcp